### ISSUE TITLE
Option to `chmod` all files created by itchy

### ISSUE THREAD

**Issue by arax** [CESNET/itchy#4]
- [x] Directories
- [x] Images
- [x] Descriptors

```yaml
file-permissions: 0660
```

**Comment by kosoburak** [comment]
--> pull request. As we discussed, I added option to set permissions only for files, not for directories. After checking pull request and merging, feel free to close this one.

**Comment by arax** [comment]
Ok, changes merged. Next time, please, consider:
* not using your master branch for pull requests
* adding 'Issue USER/REPO#ISSUE_NUMBER' to the appropriate commit message; in some cases, it's alright to close the issue directly (using the keyword "Fixes" or "Closes")

Thanks!
